[package]
name = "refraction-calc"
version = "0.4.0"
authors = ["Bartłomiej Kamiński <fizyk20@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.*"
atm-refraction = { path = "../atm-refraction" }
